---
platform: linux

image: docker:///golang#1.7-alpine

inputs:
- name: source
  path: gopath/src/github.com/ecsteam/docker-usage

outputs:
- name: gopath-tested

run:
  path: gopath/src/github.com/ecsteam/docker-usage/ci/tasks/do-test.sh
